version: 1.2.0.{build}

configuration: Release

os: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true



before_build:
  - dotnet --info
  - dotnet restore .\src\OaktonSample\OaktonSample.csproj
  - dotnet restore .\src\CommonAssemblyInfo\CommonAssemblyInfo.csproj
  - dotnet restore .\src\Oakton.Testing\Oakton.Testing.csproj

after_build:
  - dotnet pack .\src\Oakton -o artifacts --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%

test_script:
  - dotnet test .\src\Oakton.Testing\Oakton.Testing.csproj --framework netcoreapp1.1 --configuration Release

artifacts:
  - path: '**\Oakton.*.nupkg' # find all NuGet packages recursively