name: Publish Nugets

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build src/Oakton/Oakton.csproj --configuration Release

    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Oakton/Oakton.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
